inherit_from: .rubocop_todo.yml

# Rubocop configuration file

# Exclude every directory except /app
AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - coverage/**/*
    - db/**/*
    - lib/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - spec/**/*
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
